(()=>{
  const supported=new Set(["it","en","es"]),locales={it:"it-IT",en:"en-GB",es:"es-ES"};
  let language=supported.has(localStorage.getItem("cryptoRadarLanguage"))?localStorage.getItem("cryptoRadarLanguage"):"it",dictionary={},partial=[],applying=false;
  const originals=new WeakMap(),attributeOriginals=new WeakMap();
  const normalize=value=>String(value??"").replace(/\s+/g," ").trim();
  function translated(value){const key=normalize(value);if(!key||language==="it")return key;let result=dictionary[key];if(result)return result;if(key.length<12)return key;result=key;for(const [source,target] of partial){if(source.length>=12&&result.includes(source))result=result.split(source).join(target)}return result}
  function translateTextNode(node){if(!originals.has(node))originals.set(node,node.nodeValue);const original=originals.get(node),trimmed=normalize(original);if(!trimmed)return;const output=language==="it"?trimmed:translated(trimmed),left=original.match(/^\s*/)?.[0]||"",right=original.match(/\s*$/)?.[0]||"";node.nodeValue=`${left}${output}${right}`}
  function translateAttributes(element){if(!attributeOriginals.has(element)){const record={};for(const name of ["placeholder","title","aria-label"]){if(element.hasAttribute?.(name))record[name]=element.getAttribute(name)}attributeOriginals.set(element,record)}const record=attributeOriginals.get(element);for(const [name,original] of Object.entries(record))element.setAttribute(name,language==="it"?original:translated(original))}
  function translateRoot(root=document.body){if(!root||applying)return;applying=true;try{const elements=[];if(root.nodeType===Node.ELEMENT_NODE)elements.push(root);root.querySelectorAll?.("*").forEach(element=>elements.push(element));for(const element of elements){if(element.closest?.("[data-no-i18n]")||["SCRIPT","STYLE","CODE","PRE"].includes(element.tagName))continue;translateAttributes(element);for(const node of element.childNodes)if(node.nodeType===Node.TEXT_NODE)translateTextNode(node)}}finally{applying=false}}
  async function setLanguage(next){language=supported.has(next)?next:"it";localStorage.setItem("cryptoRadarLanguage",language);document.documentElement.lang=language;const select=document.getElementById("languageSelect");if(select)select.value=language;if(language==="it"){dictionary={};partial=[];translateRoot();document.dispatchEvent(new CustomEvent("crypto-radar-language",{detail:{language}}));return}try{const response=await fetch(`/i18n-${language}.json`,{cache:"force-cache"});dictionary=await response.json();partial=Object.entries(dictionary).filter(([source,target])=>source!==target&&source.length>=12).sort((a,b)=>b[0].length-a[0].length);translateRoot();document.dispatchEvent(new CustomEvent("crypto-radar-language",{detail:{language}}))}catch{dictionary={};partial=[]}}
  function init(){const select=document.getElementById("languageSelect");if(select)select.onchange=event=>setLanguage(event.target.value);setLanguage(language);const observer=new MutationObserver(records=>{if(applying)return;for(const record of records)for(const node of record.addedNodes){if(node.nodeType===Node.TEXT_NODE)translateTextNode(node);else if(node.nodeType===Node.ELEMENT_NODE)translateRoot(node)}});observer.observe(document.body,{childList:true,subtree:true})}
  window.CryptoRadarI18n={setLanguage,translateDocument:()=>translateRoot(),translate:translated,language:()=>language,locale:()=>locales[language]||locales.it};
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
